FROM hominidae/armhf-ubuntu:latest
MAINTAINER Alexey Raga <alexey.raga@gmail.com>

RUN apt-get update && apt-get upgrade -y

RUN apt-get install -y curl wget

RUN apt-get install python-software-properties -y
RUN apt-get install software-properties-common -y